tracker:
  type: bytetrack
  track_thresh: 0.5
  track_buffer: 30
  match_thresh: 0.8
  min_box_area: 10
  mot20: false
  frame_rate: 30
inputs:
  detector_weights: models/best.pt
  data_config: configs/yolo_data.yaml

